data_source bronze_staging:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_STAGINGSCHEMA}

data_source dwh:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_DWHSCHEMA}

data_source mart_customer_support:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_MARTCSSCHEMA}

data_source mart_finance:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_MARTFNSCHEMA}

data_source mart_logistic:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_MARTLGSCHEMA}

data_source mart_product:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_MARTPDSCHEMA}

data_source mart_sales:
  type: postgres
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  database: ${PGDATABASE}
  schema: ${SODA_MARTPDSCHEMA}